import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
/**
 * Componente lista de productos
 * Cumple con REQ-F01: Consulta de productos
 * Cumple con REQ-F02: Acceso a lotes del producto
 */
export var ProductList = function (_a) {
    var products = _a.products, onEdit = _a.onEdit, onDelete = _a.onDelete, onSelectProduct = _a.onSelectProduct, searchQuery = _a.searchQuery;
    if (products.length === 0) {
        return (_jsx("div", { className: "bg-white rounded-lg shadow-md p-8 text-center", children: _jsx("p", { className: "text-gray-500 text-lg", children: searchQuery ? 'No se encontraron productos.' : 'No hay productos registrados. ¡Crea uno nuevo!' }) }));
    }
    return (_jsxs("div", { className: "bg-white rounded-lg shadow-md overflow-hidden", children: [_jsx("div", { className: "overflow-x-auto", children: _jsxs("table", { className: "w-full", children: [_jsx("thead", { children: _jsxs("tr", { className: "bg-gray-100 border-b", children: [_jsx("th", { className: "px-6 py-3 text-left text-sm font-semibold text-gray-700", children: "C\u00F3digo" }), _jsx("th", { className: "px-6 py-3 text-left text-sm font-semibold text-gray-700", children: "Nombre" }), _jsx("th", { className: "px-6 py-3 text-left text-sm font-semibold text-gray-700", children: "Descripci\u00F3n" }), _jsx("th", { className: "px-6 py-3 text-left text-sm font-semibold text-gray-700", children: "Categor\u00EDa" }), _jsx("th", { className: "px-6 py-3 text-left text-sm font-semibold text-gray-700", children: "Unidad" }), _jsx("th", { className: "px-6 py-3 text-left text-sm font-semibold text-gray-700", children: "Acciones" })] }) }), _jsx("tbody", { children: products.map(function (product) { return (_jsxs("tr", { className: "border-b hover:bg-gray-50 transition-colors", children: [_jsx("td", { className: "px-6 py-4 text-sm font-medium text-gray-900", children: product.code }), _jsx("td", { className: "px-6 py-4 text-sm text-gray-700", children: product.name }), _jsx("td", { className: "px-6 py-4 text-sm text-gray-600 max-w-xs truncate", children: product.description }), _jsx("td", { className: "px-6 py-4 text-sm", children: _jsx("span", { className: "inline-block bg-blue-100 text-blue-800 rounded-full px-3 py-1 text-xs font-medium", children: product.category }) }), _jsx("td", { className: "px-6 py-4 text-sm text-gray-700", children: product.unit }), _jsx("td", { className: "px-6 py-4 text-sm", children: _jsxs("div", { className: "flex gap-2", children: [onSelectProduct && (_jsx("button", { onClick: function () { return onSelectProduct(product); }, className: "px-3 py-1 bg-purple-500 text-white text-xs rounded hover:bg-purple-600 transition-colors font-medium", title: "Ver lotes del producto", children: "Lotes" })), _jsx("button", { onClick: function () { return onEdit(product); }, className: "px-3 py-1 bg-blue-500 text-white text-xs rounded hover:bg-blue-600 transition-colors font-medium", children: "Editar" }), _jsx("button", { onClick: function () {
                                                        if (window.confirm("\u00BFEliminar producto \"".concat(product.name, "\"?"))) {
                                                            onDelete(product.id);
                                                        }
                                                    }, className: "px-3 py-1 bg-red-500 text-white text-xs rounded hover:bg-red-600 transition-colors font-medium", children: "Eliminar" })] }) })] }, product.id)); }) })] }) }), _jsxs("div", { className: "px-6 py-3 bg-gray-50 border-t text-sm text-gray-600", children: ["Total: ", _jsx("span", { className: "font-semibold", children: products.length }), " producto(s)"] })] }));
};
